import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },

    {
      name: 'CHARGEUR DE BATTERIE DE VOITURE 10 AMP 220V (6/12V) D S',
      slug: 'chargeur-de-batterie-de-voiture',
      category: 'MATÉRIELS D ÉQUIPEMENT',
      image: '/images/chargeur-de-batterie.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Chargeur de Batterie de Voiture 10 Amp 6V / 12V DFC-10P Turbo/Trickle avec Technologie de réparation et de Maintenance de la Batterie',
      banner: '/images/chargeur-de-batterie.jpg',
       },
    {
      name: 'Siemens 3VJ MCCB 100 A',
      slug: 'siemens-3vj1010',
      category: 'Low Voltage Switchgears',
      image: '/images/siemens-3vj-thermal-3pole-mccb_2.webp',
      price: 30,
      brand: 'Siemens',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Siemens 3VJ MCCB 100 A, 3 Pole, 10 kA, Fixed O/L & Fixed S/C Settings, Thermal Magnetic Trip Unit (FTFM) | 3VJ1010-0DA32-0AA0',
banner: '/images/siemens-3vj-thermal-3pole-mccb_2.webp',
       },
    {
      name: 'Havells Euro-II Microcontroller',
      slug: 'havells-euro-ii-microcontroller',
      category: 'Low Voltage Switchgears',
      image: '/images/havells-microcontroller-accl-dhadosn3004.webp',
      price: 30,
      brand: 'Havells',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Havells Euro-II Microcontroller Based ACCL EB : SPN, 30 A, DG : SPN, 4 A | DHADOSN3004',

       },
    {
      name: 'Lapp Olflex 100',
      slug: 'lapp-olflex-100',
      category: 'Wires & Cables',
      image: '/images/lapp-olflex-100l-grey-3800.webp',
      price: 30,
      brand: 'LAPP Kabel',
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'Lapp Olflex 100 I, 0.5 sq.mm, 2 Core Copper Flexible Cable, Grey, PVC FR (Flame Retardant) | 38007034',

       },
    {
      name: 'Prok dv s Protective Relay',
      slug: 'prok-dv-s-protective-relay',
      category: 'Relay',
      image: '/images/prok-earth-leakage-relay-el-tape-wound.webp',
      price: 30,
      brand: 'Prok dvs',
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'Prok dv s Protective Relay ELR With CBCT 1-8 A, 2 C/O, Tape Wound, 250 mm | EL-01-2C-T250-F',

       },
    {
      name: 'Schneider Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr',
      slug: 'schneider-electric-standart',
      category: 'Capacitors and Reactors',
      image: '/images/schneider-cylindrical-mpp-capacitor-mehvcsdy010a44.webp',
      price: 15,
      brand: 'Prok dvs',
      rating: 3.4,
      numReviews: 10,
      countInStock: 30,
      description: 'Schneider Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr, 440 V AC, 3 Phase, 50 Hz | MEHVCSDY020A44',

       },
  ],
}

export default data
