import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Ramzi',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'discout',
      slug: 'slide',
      category: 'slide',
      image: '/images/banner3.jpg',
      price: 0,
      brand: 'slide',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'slide',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'discout1',
      slug: 'slide2',
      category: 'slide',
      image: '/images/banner3.jpg',
      price: 0,
      brand: 'slide',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'slide',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    
    {
      name: 'Socomec Sircover Manual Transfer Switch 200A',
      slug: 'socomec-sircover-manual-transfer-switch-200A',
      category: 'Manual Transfer Switches',
      image: '/images/socomec-sircover-manual-transfer-switch-type-2-open-execution.webp',
      price: 90,
      brand: 'Socomec',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Socomec Sircover Manual Transfer Switch 200A, 3 Pole, 415 V AC, Frame B3, Kit Type 2, Open Execution | 41K23020A',
    },
    
    
    {
      name: 'Car battery charger 10 AMP 6V / 12V DFC-10P Turbo / Trickle with repair and battery maintenance technology',
      slug: 'car-battery-charger',
      category: 'Equipment',
      image: '/images/chargeur-de-batterie.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Car battery charger 10 AMP 6V / 12V DFC-10P Turbo / Trickle with repair and battery maintenance technology',
     
       },
    {
      name: 'Siemens 3VJ MCCB 100 A',
      slug: 'siemens-3vj1010',
      category: 'Low Voltage Switchgears',
      image: '/images/siemens-3vj-thermal-3pole-mccb_2.webp',
      price: 30,
      brand: 'Siemens',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Siemens 3VJ MCCB 100 A, 3 Pole, 10 kA, Fixed O/L & Fixed S/C Settings, Thermal Magnetic Trip Unit (FTFM) | 3VJ1010-0DA32-0AA0',
banner: '/images/siemens-3vj-thermal-3pole-mccb_2.webp',
       },
    {
      name: 'Havells Euro-II Microcontroller',
      slug: 'havells-euro-ii-microcontroller',
      category: 'Low Voltage Switchgears',
      image: '/images/havells-microcontroller-accl-dhadosn3004.webp',
      price: 30,
      brand: 'Havells',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Havells Euro-II Microcontroller Based ACCL EB : SPN, 30 A, DG : SPN, 4 A | DHADOSN3004',

       },
    {
      name: 'Lapp Olflex 100',
      slug: 'lapp-olflex-100',
      category: 'Wires & Cables',
      image: '/images/lapp-olflex-100l-grey-3800.webp',
      price: 30,
      brand: 'LAPP Kabel',
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'Lapp Olflex 100 I, 0.5 sq.mm, 2 Core Copper Flexible Cable, Grey, PVC FR (Flame Retardant) | 38007034',

       },
    {
      name: 'Prok dv s Protective Relay',
      slug: 'prok-dv-s-protective-relay',
      category: 'Relay',
      image: '/images/prok-earth-leakage-relay-el-tape-wound.webp',
      price: 30,
      brand: 'Prok dvs',
      rating: 4.4,
      numReviews: 10,
      countInStock: 20,
      description: 'Prok dv s Protective Relay ELR With CBCT 1-8 A, 2 C/O, Tape Wound, 250 mm | EL-01-2C-T250-F',

       },
    {
      name: 'Schneider Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr',
      slug: 'schneider-electric-standart',
      category: 'Capacitors and Reactors',
      image: '/images/schneider-cylindrical-mpp-capacitor-mehvcsdy010a44.webp',
      price: 15,
      brand: 'Prok dvs',
      rating: 3.4,
      numReviews: 10,
      countInStock: 30,
      description: 'Schneider Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr, 440 V AC, 3 Phase, 50 Hz | MEHVCSDY020A44',

       },
    {
      name: 'Schneider1 Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr',
      slug: 'schneider1-electric-standart',
      category: 'Capacitors and Reactors',
      image: '/images/schneider-cylindrical-mpp-capacitor-mehvcsdy010a44.webp',
      price: 15,
      brand: 'Prok dvs',
      rating: 3.4,
      numReviews: 10,
      countInStock: 30,
      description: 'Schneider Electric EasyCan Standard Duty Round/Cylindrical MPP Capacitor 2 KVAr, 440 V AC, 3 Phase, 50 Hz | MEHVCSDY020A44',

       },
  ],
}

export default data
